In [1]:
from wwo_hist import retrieve_hist_data
import pandas as pd
import os
import os.path
import regex

# Loading original data set 

FILE_PATH = os.path.abspath(os.path.dirname('other_data/final.csv'))
cities = pd.read_csv(FILE_PATH + '/final.csv')
cities.replace('\s+', '_',regex=True,inplace=True)
cities

,City,State,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,...,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10,Air Quality Index,Diversity Index,Nearest,lat,lon
0,Akron,OH,267782,129623,138086,1.9,67.4,23.2,0.2,3.6,...,0,132,0,142,0,Good,0.490241,"126,56,332,355,295",41.044852,-81.520048
1,Albany,GA,93421,43571,49835,2.8,29.2,65.2,0.1,0.9,...,0,0,0,244,0,Good,0.488771,"162,372,139,351,249",31.567783,-84.161923
2,Albany,NY,147794,70664,77096,7.8,60.3,20.1,0.1,7.6,...,0,169,0,104,0,Good,0.584133,"319,358,336,145,79",42.652580,-73.756633
3,Albany,OR,61555,30378,31168,11.4,82.7,0.6,0.7,1.9,...,0,0,0,182,0,Good,0.302632,"29,132,230,383,202",44.627722,-123.094409
4,Albuquerque,NM,632240,309415,322758,50.4,38.5,2.5,4.0,2.4,...,0,127,0,25,30,Good,0.594958,"359,258,386,360,127",35.106766,-106.629181
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,Worcester,MA,183628,89977,93611,20.8,57.2,11.7,0.3,7.3,...,6,169,0,61,1,Good,0.610528,"186,362,6,391,266",42.271389,-71.798889
393,Wyoming,MI,56377,27516,28855,23.8,62.0,7.1,0.4,2.3,...,0,131,0,50,0,Good,0.553378,"131,153,330,209,282",42.900867,-85.705775
394,Yakima,WA,125036,61639,63374,40.1,54.1,0.9,1.6,1.0,...,0,0,0,243,1,Good,0.546085,"256,383,202,320,230",46.606991,-120.477336
395,Yuba_City,CA,75848,37647,38198,28.2,46.2,2.1,0.6,17.7,...,0,149,0,63,1,Good,0.675218,"267,368,255,354,392",39.128619,-121.621599
396,Yuma,AZ,142402,73123,69270,52.5,40.9,2.4,0.8,1.5,...,0,198,0,45,31,Good,0.556232,"329,134,350,368,130",32.701507,-114.642362

In [2]:
# Load data set retrievd from weatheronline
FILE_PATH = os.path.abspath(os.path.dirname('merged_cities.csv'))
cities_df = pd.read_csv(FILE_PATH + '/merged_cities.csv')
cities_df

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,moon_illumination,moonrise,moonset,sunrise,...,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph,location
0,2018-01-01 00:00:00,1,-4,0.0,10.0,1,97,06:38 PM,07:47 AM,08:27 AM,...,34,93,57,0.0,1037,-2,10,9,25,Austin
1,2018-01-01 03:00:00,1,-4,0.0,10.0,1,97,06:38 PM,07:47 AM,08:27 AM,...,36,37,48,0.0,1038,-3,10,17,26,Austin
2,2018-01-01 06:00:00,1,-4,0.0,10.0,1,97,06:38 PM,07:47 AM,08:27 AM,...,30,31,41,0.0,1040,-4,10,12,23,Austin
3,2018-01-01 09:00:00,1,-4,0.0,10.0,1,97,06:38 PM,07:47 AM,08:27 AM,...,31,68,37,0.0,1041,-3,10,20,24,Austin
4,2018-01-01 12:00:00,1,-4,0.0,10.0,1,97,06:38 PM,07:47 AM,08:27 AM,...,21,33,30,0.0,1040,0,10,10,18,Austin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818475,2021-02-28 09:00:00,10,2,0.0,11.2,3,82,08:23 PM,08:20 AM,07:12 AM,...,34,1,25,0.0,1027,3,10,221,19,Las_Vegas
818476,2021-02-28 12:00:00,10,2,0.0,11.2,3,82,08:23 PM,08:20 AM,07:12 AM,...,25,0,14,0.0,1026,7,10,5,18,Las_Vegas
818477,2021-02-28 15:00:00,10,2,0.0,11.2,3,82,08:23 PM,08:20 AM,07:12 AM,...,21,0,12,0.0,1024,9,10,127,15,Las_Vegas
818478,2021-02-28 18:00:00,10,2,0.0,11.2,3,82,08:23 PM,08:20 AM,07:12 AM,...,17,0,13,0.0,1024,10,10,350,12,Las_Vegas
818479,2021-02-28 21:00:00,10,2,0.0,11.2,3,82,08:23 PM,08:20 AM,07:12 AM,...,11,0,17,0.0,1025,10,10,338,8,Las_Vegas

In [3]:
# Renamed column to match the other dataset and to be able to merge them on a primary key 
cities_df = cities_df.rename(columns={"location": "City"})
cities_df

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,moon_illumination,moonrise,moonset,sunrise,...,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph,City
0,2018-01-01 00:00:00,1,-4,0.0,10.0,1,97,06:38 PM,07:47 AM,08:27 AM,...,34,93,57,0.0,1037,-2,10,9,25,Austin
1,2018-01-01 03:00:00,1,-4,0.0,10.0,1,97,06:38 PM,07:47 AM,08:27 AM,...,36,37,48,0.0,1038,-3,10,17,26,Austin
2,2018-01-01 06:00:00,1,-4,0.0,10.0,1,97,06:38 PM,07:47 AM,08:27 AM,...,30,31,41,0.0,1040,-4,10,12,23,Austin
3,2018-01-01 09:00:00,1,-4,0.0,10.0,1,97,06:38 PM,07:47 AM,08:27 AM,...,31,68,37,0.0,1041,-3,10,20,24,Austin
4,2018-01-01 12:00:00,1,-4,0.0,10.0,1,97,06:38 PM,07:47 AM,08:27 AM,...,21,33,30,0.0,1040,0,10,10,18,Austin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818475,2021-02-28 09:00:00,10,2,0.0,11.2,3,82,08:23 PM,08:20 AM,07:12 AM,...,34,1,25,0.0,1027,3,10,221,19,Las_Vegas
818476,2021-02-28 12:00:00,10,2,0.0,11.2,3,82,08:23 PM,08:20 AM,07:12 AM,...,25,0,14,0.0,1026,7,10,5,18,Las_Vegas
818477,2021-02-28 15:00:00,10,2,0.0,11.2,3,82,08:23 PM,08:20 AM,07:12 AM,...,21,0,12,0.0,1024,9,10,127,15,Las_Vegas
818478,2021-02-28 18:00:00,10,2,0.0,11.2,3,82,08:23 PM,08:20 AM,07:12 AM,...,17,0,13,0.0,1024,10,10,350,12,Las_Vegas
818479,2021-02-28 21:00:00,10,2,0.0,11.2,3,82,08:23 PM,08:20 AM,07:12 AM,...,11,0,17,0.0,1025,10,10,338,8,Las_Vegas

In [6]:
# Merging 2 datasets on 'city', which is a primary key. 
cities_combined = pd.merge(cities, cities_df, on='City', how='outer')
cities_combined

MemoryError: Unable to allocate 99.9 MiB for an array with shape (16, 818480) and data type int64